# Generated by Django 2.1.2 on 2018-11-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorway_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorwayevent',
            name='event_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
