# Generated by Django 2.1.2 on 2018-11-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorway_api', '0002_auto_20181104_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorwayevent',
            name='time_timestamp',
            field=models.DateTimeField(),
        ),
    ]
