# Generated by Django 2.1.2 on 2018-11-04 14:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorway_api', '0003_auto_20181104_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorwayevent',
            name='closest_cities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='motorwayevent',
            name='junction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), size=3),
        ),
    ]
