# Generated by Django 2.1.2 on 2018-11-04 15:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorway_api', '0004_auto_20181104_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorwayevent',
            name='junction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=3),
        ),
    ]
