# Generated by Django 2.1.2 on 2018-11-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorway_api', '0005_auto_20181104_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorwayevent',
            name='extra_information',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
