# Generated by Django 2.1.2 on 2018-11-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorway_api', '0006_motorwayevent_extra_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorwayevent',
            name='extra_information',
        ),
    ]
