# Generated by Django 2.1.2 on 2018-11-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorway_api', '0007_remove_motorwayevent_extra_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorwayevent',
            name='extra_information',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
