# Generated by Django 2.1.2 on 2018-11-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorway_api', '0008_motorwayevent_extra_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorwayevent',
            name='time_day_worded',
            field=models.CharField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=3),
        ),
    ]
