# Generated by Django 2.1.2 on 2019-02-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorway_api', '0009_auto_20181117_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorwayevent',
            name='time_day_numerical',
        ),
        migrations.AddField(
            model_name='motorwayevent',
            name='time_day',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motorwayevent',
            name='direction',
            field=models.CharField(choices=[('n', 'n'), ('s', 's'), ('e', 'e'), ('w', 'w'), ('c', 'c'), ('ac', 'ac')], max_length=1),
        ),
        migrations.AlterField(
            model_name='motorwayevent',
            name='motorway',
            field=models.CharField(choices=[(1, 1), (6, 6), (25, 25), (40, 40)], max_length=4),
        ),
        migrations.AlterField(
            model_name='motorwayevent',
            name='time_hour',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='motorwayevent',
            name='time_minutes',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='motorwayevent',
            name='time_seconds',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='motorwayevent',
            name='time_year',
            field=models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019')], max_length=4),
        ),
    ]
