# Generated by Django 2.1.2 on 2019-03-10 15:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorway_api', '0010_auto_20190228_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorwayevent',
            name='extra_information',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None),
        ),
    ]
