version: "3"
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./src/motorway_project:/app
    working_dir: "/app/"