version: "2.3"
services:
  # Ensure to source db-config.sh
  motorway_api:
    build: ./motorway_project
    command: python3 manage.py runserver 0.0.0.0:8000
    #depends_on:
    #  motorway_db:
    #    condition: "service_healthy"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    network_mode: "host"
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - /home/suhailparmar/Projects/MotorwayAPI/motorway_project:/app/
    working_dir: "/app/"

  motorway_db:
    build: ./motorway_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:5432"]
    #  interval: 10s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 5s
    network_mode: "host"
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./motorway_db/pg_data:/var/lib/postgresql/data