from django.test import TestCase
from rest_framework.test import APIClient
from rest_framework import status
from django.urls import reverse
import json
import pytest


class TestEventsEndpoint():

    client = APIClient()
    # Motorway Tweet Converter
    json_payload = {
        "closest_cities": [
            "Stafford (N)",
            "Stoke / Newcastle-u-Lyme"
        ],
        "direction": "n",
        "extra_information": [],
        "event_id": 1052482906797428737,
        "junction": "14,15",
        "metadata": "Event Generated by Tweet Miner at 2018-10-20T20:50:12.286910",
        "motorway": 6,
        "reason": "congestion",
        "time_day_numerical": 17,
        "time_day_worded": "Wed",
        "time_hour": 8,
        "time_minutes": 54,
        "time_seconds": 13,
        "time_timestamp": "2018-10-17T08:54:13",
        "time_year": 2018
    }

    @pytest.mark.django_db
    def test_post_event_successful(self):

        response = self.client.post(
            reverse('create'),
            data=self.json_payload,
            format="json"
        )

        print(json.dumps(response.data, indent=4))
        assert response.status_code == status.HTTP_201_CREATED
